name: Create Release

on:
    pull_request:
      branches:
        - main
      types:
        - closed

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_BOT_ACC_EMAIL: guillaume.papineau@epitech.eu
    GH_BOT_ACC_NAME: github-actions[bot]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check if PR is merged to main
        id: pr-check
        run: |
          merged=$(jq -r '.pull_request.merged' $GITHUB_EVENT_PATH)
          echo "merged=$merged" >> $GITHUB_OUTPUT

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up Git
        run: |
            git config --local user.email $GH_BOT_ACC_EMAIL
            git config --local user.name $GH_BOT_ACC_NAME

      - name: Authenticate GitHub CLI
        run: |
          echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Increment Version
        if: steps.pr-check.outputs.merged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          current_version=$(cat VERSION)
          new_version=$(python3 increment_version.py $current_version)
          echo "$new_version" > VERSION
          git add VERSION
          git commit -m "chore(VERSION): bump version to $new_version" || true
          git push origin main || true

      - name: Create Tag and Release
        if: success() && steps.pr-check.outputs.merged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a v$new_version -m "LplKernel v$new_version"
          git push origin v$new_version || true
          gh release create v$new_version || true
