name: Linter GitHub Action

on:
  push:
    branches-ignore: [ga-ignore-**, gh-pages]
    paths:
      - '**.c'
      - '**.h'
      - '.github/workflows/linter.yml'

permissions:
  contents: write

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_code:
    name: Lint with clang-format (auto-apply)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Find tracked C files
        id: files
        run: |
          git ls-files '*.c' '*.h' > tracked_files.txt || true
          echo "files<<EOF" >> $GITHUB_OUTPUT
          sed 's/\"/\\\"/g' tracked_files.txt | sed -z 's/\n/\\n/g' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Ensure newline at EOF and run clang-format
        if: steps.files.outputs.files != ''
        run: |
          git ls-files '*.c' '*.h' | while IFS= read -r f; do
            tail -c1 < "$f" | read -r _ || echo >> "$f"
            clang-format -i "$f"
          done

      - name: Show git status
        run: |
          git status --porcelain

      - name: Commit and push style changes
        if: ${{ steps.files.outputs.files != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No formatting changes to commit."
            exit 0
          fi
          git commit -m "style: apply clang-format" || true
          git pull --rebase origin main || true
          git push origin HEAD:main
